### ISSUE TITLE
Duplicate ids found on mask elements

### ISSUE THREAD

**Issue by blowsie** [opudalo/optimize-images-figma-plugin#4]
Hi, I exported a bunch of flags using the default settings (prefixIds on) and there are still some duplicated IDs on mask elements

![image](https://user-images.githubusercontent.com/308572/89832819-cdd2bf80-db57-11ea-9fd2-3f79b96e476c.png)

**Comment by opudalo** [comment]
If you'll share a figma file with those components to reproduce – that would be great help.

**Comment by blowsie** [comment]
Sure :)
[flags.zip](https://github.com/okotoki/advanced-svg-export/files/5057496/flags.zip)

**Comment by opudalo** [comment]
closed due to my inactivity actively developing this project
