### ISSUE TITLE
Feature request: Enable setting "Precision" for export settings.

### ISSUE THREAD

**Issue by jchiem** [opudalo/optimize-images-figma-plugin#9]
Hello
I'd like to request that a feature is added to the plugin, a new option to set global [floatPrecision](https://github.com/svg/svgo/blob/3d79f57a10d7b3dba4bcd30d0b94e22410626cae/lib/svgo/config.js#L81) like how it's done in [svgomg](https://github.com/jakearchibald/svgomg/blob/82c92f6ccc9f124549d94c182c9d5ad5e8431830/src/js/svgo-worker/index.js#L226)

### Background
The reason for this request is that when my team were trying to export svgs for usage in iOS we realized that the `Round/rewrite paths` was in many cases totally breaking the `svgs`. When I tested this out in [svgomg](https://jakearchibald.github.io/svgomg/) and tuned the precision to be higher than 3 it was possible to use the exported `.svg` in iOS. 

**Screenshots taken within xcode.**

Original SVG exported through Figma without plugin:

<img width="125" alt="original" src="https://user-images.githubusercontent.com/3385622/116551140-e65a5400-a8f7-11eb-8197-986df6157cc8.png">

With floating precision set to 3 (default):
<img width="119" alt="three" src="https://user-images.githubusercontent.com/3385622/116551142-e6f2ea80-a8f7-11eb-9f45-ecd03e694ade.png">

With floating precision set to 4 from svgomg:
<img width="120" alt="four" src="https://user-images.githubusercontent.com/3385622/116551137-e5c1bd80-a8f7-11eb-86b4-673171f3bfeb.png">

**Comment by opudalo** [comment]
I'm not actively maintaining this project currently.
Feel free to contribute.
